### ISSUE TITLE
Run Function locally.

### ISSUE THREAD

**Issue by dimasanwaraziz** [ItzNotABug/appexpress#23]
How can I run this function locally without push to Appwrite first.

**Comment by ItzNotABug** [comment]
Hey @dimasanwaraziz 👋,
1. If you have a self hosted appwrite instance on your machine then you could push the function there.
2. If you intend to test the project locally, I do that for tests by creating a pseudo `context`. Take a look [here](https://github.com/ItzNotABug/appexpress/blob/master/source/tests/test.js) and [here](https://github.com/ItzNotABug/appexpress/blob/master/source/tests/utils/context.js).

Ofc to have a full fledged drop in support to test this without Appwrite, you'd need to extend the headers for the context, which can be seen [here](https://github.com/open-runtimes/open-runtimes/blob/16bf063b60f1f2a150b6caa9afdd2d1786e7ca35/runtimes/node-18.0/src/server.js#).

**Comment by dimasanwaraziz** [comment]
Okay, thank's for your response, I'll discover this first.

**Comment by ItzNotABug** [comment]
@dimasanwaraziz Can this be closed?

**Comment by dimasanwaraziz** [comment]
Yes you can close this case, thanks.
