### ISSUE TITLE
response.status is not a function

### ISSUE THREAD

**Issue by dimasanwaraziz** [ItzNotABug/appexpress#33]
For [express 4.x](https://expressjs.com/en/api.html#res.json) status is `res.status(500).json({ error: 'message' })` 

But I see on [this documentation](https://github.com/ItzNotABug/appexpress/wiki/Request-&-Response) the response not include with status. 

So when implement same code when switching from express to appexpress, it's return error.
<img width="952" alt="image" src="https://github.com/ItzNotABug/appexpress/assets/50611785/00eb86d4-adc6-4bbb-90c4-54b3b9066a6e">

**Comment by ItzNotABug** [comment]
Hey 👋 ,
`AppExpress`' syntax isn't completely same as `express.js` but rather similar to what Appwrite's Functions have.

You can do this way -
```javascript
response.json({ error: 'message' }, 500)
```

**Comment by ItzNotABug** [comment]
Hey @dimasanwaraziz,
Is your issue resolved now?

**Comment by dimasanwaraziz** [comment]
Yes, I can use the another way like you say.

But nice to have if we have that feature same like express.

**Comment by ItzNotABug** [comment]
> Yes, I can use the another way like you say.
> 
> But nice to have if we have that feature same like express.

A fair point but `express.js` uses chaining which isn't what I'd prefer atm.
I would instead like to keep it as close to the Appwrite Function's behaviour.
