### ISSUE TITLE
[FEATURE REQUEST]: Middleware for a specific route.

### ISSUE THREAD

**Issue by moshOntong-IT** [ItzNotABug/appexpress#38]
The package includes the `Middleware` feature, which currently applies to all routes. However, it would be beneficial if `AppExpress` could add middleware to specific routes only. Perhaps introducing a `next` parameter in the middleware function could be also a good idea.  For instance, the `Express Package` utilizes this `next` parameter:

```
const express = require('express')
const app = express()

app.use((req, res, next) => {
  console.log('Time:', Date.now())
  next()
})
```

**Comment by moshOntong-IT** [comment]
Is it possible to return res.res or any kind of return response within middleware. As of now, we use `throw Error()` so it will indicate that there are some error on middleware. But can we just return res.send/res.json and etc. Because it is good that we can return a status code of the error. For example, I have a middleware then I want to throw an error that 'No found' so I can use a `return res.send("No Found", 404)`

**Comment by ItzNotABug** [comment]
Hey @moshOntong-IT 👋,
Thanks for this neat suggestion!

---
Coming to your next question -
Absolutely. Every middleware you register can `return` values via `send`, `json`, etc. and end the process at that time.

You can do something like this -
```js
express.middleware((request, response, log, error) => {
  const { userJwtToken } = req.body; // example token.
  const isDashboard = req.path.includes('/dashboard');
  
  if(isDashboard && !userJwtToken) {
    response.send("Not Found", 404); // hiding the dashboard for unauthenticated users.
  }
});
```

**Comment by ItzNotABug** [comment]
@moshOntong-IT 
Once you do a `response.send` call (as shown above). The request ends there.

**Comment by CodeMode365** [comment]
> Is it possible to return res.res or any kind of return response within middleware. As of now, we use `throw Error()` so it will indicate that there are some error on middleware. But can we just return res.send/res.json and etc. Because it is good that we can return a status code of the error. For example, I have a middleware then I want to throw an error that 'No found' so I can use a `return res.send("No Found", 404)`

I think sending response through middlewawre is possible

import axios from "axios";

export const authMiddleware = async (req, res, next) => {
    try {
        const cookies = req.headers.cookie;
        if (!cookies) {
            return res.json({ message: "Missing auth token" }, 401);
        }

        const token = cookies.split("; ").find(cookie => cookie.startsWith("token="));

        if (!token) {
            return res.json({ message: "Missing Token auth token" }, 401);
        }

        try {
            const response = await axios.get(`${process.env.AUTH_SERVER}/api/session`, {
                headers: { Cookie: token }
            });

            req.user = response.data;
            next();

        } catch (error) {
            console.error("Authentication failed:", error.message, error);
            return res.json({ message: "Invalid auth token" }, 401);
        }

    } catch (error) {
        console.error("Server error:", error.message);
        return res.json({ message: "Server error" }, 500);
    }
};

**Comment by ItzNotABug** [comment]
> I think sending response through middlewawre is possible
> 
> ```
> import axios from "axios";
> 
> export const authMiddleware = async (req, res, next) => {
>     try {
>         const cookies = req.headers.cookie;
>         if (!cookies) {
>             return res.json({ message: "Missing auth token" }, 401);
>         }
> 
>         const token = cookies.split("; ").find(cookie => cookie.startsWith("token="));
> 
>         if (!token) {
>             return res.json({ message: "Missing Token auth token" }, 401);
>         }
> 
>         try {
>             const response = await axios.get(`${process.env.AUTH_SERVER}/api/session`, {
>                 headers: { Cookie: token }
>             });
> 
>             req.user = response.data;
>             next();
> 
>         } catch (error) {
>             console.error("Authentication failed:", error.message, error);
>             return res.json({ message: "Invalid auth token" }, 401);
>         }
> 
>     } catch (error) {
>         console.error("Server error:", error.message);
>         return res.json({ message: "Server error" }, 500);
>     }
> };
> ```
> 
> this code is working fine when i use app.middleware(authMiddleware) in production too

It is possible, but remember that there's no `next()` in AppExpress.
Consult the [docs](https://github.com/ItzNotABug/appexpress/wiki/Middlewares) on how to create custom middlewares for your usecases.

**Comment by ItzNotABug** [comment]
Its currently possible to do something like this -
```ts
express.middleware((request, response, log, error) => {
  const requiresInterception = request.path.includes('/api');

  if (requiresInterception) {
    // apply some response logic here, or do some logging with `log` or `error` functions.
  } else {
    // ignore the request
  }
});
```

I don't want to make current middleware handling logic more complex at this time. Closing for now.
